const galleryData = [
  { src: "../../gallery/1.png", alt:"1" },
  { src: "../../gallery/2.png", alt:"2" },
  { src: "../../gallery/3.png", alt:"3" },
  { src: "../../gallery/4.png", alt:"4" },
  { src: "../../gallery/5.png", alt:"5" },
  { src: "../../gallery/6.png", alt:"6" },
  { src: "../../gallery/7.png", alt:"7" },
  { src: "../../gallery/8.png", alt:"8" },
  { src: "../../gallery/9.png", alt:"9" },
  { src: "../../gallery/10.png", alt:"10" },
  { src: "../../gallery/11.png", alt:"11" },
  { src: "../../gallery/12.png", alt:"12" },
  { src: "../../gallery/13.png", alt:"13" },
  { src: "../../gallery/14.png", alt:"14" },
  { src: "../../gallery/15.jpg", alt:"15" },
  { src: "../../gallery/16.png", alt:"16" },
  { src: "../../gallery/17.png", alt:"17" },
  { src: "../../gallery/18.png", alt:"18" },
  { src: "../../gallery/19.jpg", alt:"19" },
  { src: "../../gallery/20.png", alt:"20" },
  { src: "../../gallery/21.png", alt:"21" },
  { src: "../../gallery/22.png", alt:"22" },
  { src: "../../gallery/23.png", alt:"23" },
  { src: "../../gallery/24.png", alt:"24" },
  { src: "../../gallery/25.png", alt:"25" },
  { src: "../../gallery/26.png", alt:"26" },
  { src: "../../gallery/27.png", alt:"27" },
];

export default galleryData;
